title: msu
port: 8005
tabs:
    main: true
    notebook: "http://ipepdvcompute1.ipe.kit.edu:8000"
    config: true
plugins:
    text: null
    icon: null
    integer_to_string: null
    readonly: null
