title: msu
port: 8005
tab:
    page_name: ["editor", "test"]
plugins:
    # <PLUGIN_NAME>:
    #    typedef: <yaml_file_in_typedef_folder>
    #    function: <function_folder_>
    #    template: <html_stub_in_template_folder>
    #    js_plugins: <javascript_stub_> 
    - rest
    - hls
